services:
  - type: web
    name: lovepulseiras-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: prod
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    autoDeploy: true
